name: Test My Action
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: ./
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

